---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  labels:
    prometheus/shared: "true"
spec:
  jobLabel: app
  endpoints:
  - port: prometheus
    interval: 30s
    honorLabels: true
  selector:
    matchLabels:
      app: kube-state-metrics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-dashboard
  labels:
    grafana-dashboard/shared: "true"
data:
  pod-dashboard.json: |-
    {{ .Files.Get "files/pod-dashboard.json" | indent 4 | trim }}
