---
apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  labels:
    app: kube-state-metrics
spec:
  ports:
  - name: prometheus
    port: 80
    targetPort: prometheus
  selector:
    app: kube-state-metrics
