auth:
 github:
  enabled:
  allowSignUp:
  clientId:
  clientSecret:
  allowedOrganizations:

# Dns domain for Grafana
dns:
  enabled:
  domain:

# Namespace where grafana is being deployed (to be replaced .Release.Namespace eventually )
namespace:
