## config

# auth:
#  github:
#   enabled: true
#   allowSignUp: true
#   clientId: fjfjfjfjfjfjfjfjfjfj
#   clientSecret: fjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjf
#   scopes: user:email,read:org
#
# domain: example.com
# namespace: observe

dns:
  enabled: false
