---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    app: alertmanager
  {{ if .Values.dns.enabled }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: alertmanager.{{ .Values.dns.domain }}.
  {{ end }}
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: alertmanager
