---
# The prometheus operator exposes the kubelet as a service in the kube-system namespace
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubelet
  labels:
    prometheus/shared: "true"
spec:
  jobLabel: k8s-app
  endpoints:
  - port: http-metrics
    interval: 30s
  - port: cadvisor
    interval: 30s
    honorLabels: true
  selector:
    matchLabels:
      k8s-app: kubelet
  namespaceSelector:
    matchNames:
    - kube-system
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-operator
  labels:
    prometheus/shared: "true"
spec:
  groups:
    - name: ./prometheus-operator.rules
      rules:
        - alert: GrafanaDeploymentHasNoReplicasAvailable
          expr: kube_deployment_status_replicas_available{ deployment="grafana" } < 1
          for: 5m
          labels:
            severity: warning
            team: shared
          annotations:
            summary: |-
              In the namespace {{"{{"}}$labels.namespace{{"}}"}} - There is no Grafana replicas available.
              `kubectl get deployments grafana --namespace {{"{{"}}$labels.namespace{{"}}"}}`
