{
 "title": "Alert manager",
 "description": "Show current firing and pending alerts, and  severity alert counts.",
 "tags": [
  "prometheus",
  "alerts"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 11, "x": 0, "y": 0 }, "content": "# Firing" },
  { "type": "text", "gridPos": { "h": 2, "w": 11, "x": 12, "y": 0 }, "content": "# Pending" },
  { "title": "Severity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Critical [current]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(ALERTS{alertname!=\"DeadMansSwitch\",alertstate=\"firing\",severity=\"critical\"} > 0) Or On() vector(0)",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ]
    }
   ]
  },
  {
   "title": "Warning [current]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertname!=\"DeadMansSwitch\",alertstate=\"firing\", severity=\"warning\"} > 0) Or On() vector(0)"
    }
   ]
  },
  {
   "title": "Critical [current]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": " sum(ALERTS{alertname!=\"DeadMansSwitch\",alertstate=\"pending\",severity=\"critical\"} > 0) Or On() vector(0)",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ]
    }
   ]
  },
  {
   "title": "Warning [current]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertname!=\"DeadMansSwitch\",alertstate=\"pending\",severity=\"warning\"}) Or On() vector(0)"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Critical",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "ALERTS{alertname!=\"DeadMansSwitch\", alertstate='firing', severity='critical'} > 0"
    }
   ]
  },
  {
   "title": "Critical pending",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "ALERTS{alertname!=\"DeadMansSwitch\", alertstate=\"pending\", severity='critical'} > 0"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "ALERTS{alertname!=\"DeadMansSwitch\",alertstate='firing', severity='warning'} > 0"
    }
   ]
  },
  {
   "title": "Warning pending",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "ALERTS{alertname!=\"DeadMansSwitch\", alertstate=\"pending\", severity='warning'} > 0"
    }
   ]
  }
 ]
}