---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  labels:
    prometheus/shared: "true"
spec:
  endpoints:
  - interval: 30s
    port: prometheus
  selector:
    matchLabels:
      app: node-exporter
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-exporter-dashboard
  labels:
    grafana-dashboard/shared: "true"
data:
  node-exporter-dashboard.json: |-
    {{ .Files.Get "files/node-exporter-dashboard.json" | indent 4 | trim }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-exporter
  labels:
    prometheus/shared: "true"
spec:
  groups:
    - name: ./node-exporter.rules
      rules:
        - alert: NodeExporterDaemonsetIsMissingReplicas
          expr: kube_daemonset_status_number_unavailable{daemonset="node-exporter"} != 0
          for: 5m
          labels:
            severity: warning
            team: shared
          annotations:
            summary: |-
              In the namespace {{"{{"}}$labels.namespace{{"}}"}} - There is unavailable node exporters.
              `kubectl get daemonset node-exporter --namespace {{"{{"}}$labels.namespace{{"}}"}}`
