---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  labels:
    prometheus/shared: "true"
spec:
  endpoints:
  - interval: 30s
    port: prometheus
  selector:
    matchLabels:
      app: node-exporter
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-exporter-dashboard
  labels:
    grafana-dashboard/shared: "true"
data:
  node-exporter-dashboard.json: |-
    {{ .Files.Get "files/node-exporter-dashboard.json" | indent 4 | trim }}
