---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  clusterIP: None
  ports:
  - name: prometheus
    port: 80
    targetPort: prometheus
  selector:
    app: node-exporter
