apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
  annotations:
    external-dns.alpha.kubernetes.io/hostname: prometheus.{{ .Values.prometheus.domain }}.
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 9090
  selector:
    app: prometheus
