apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
  {{ if .Values.dns.enabled }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: prometheus.{{ .Values.dns.domain }}.
  {{ end }}
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 9090
  selector:
    app: prometheus
