---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
data:
  custom.ini: |-
    [server]
    root_url = http://grafana.{{ .Values.dns.domain }}

    [auth]
    disable_login_form = true

    [users]
    auto_assign_org = true
    auto_assign_org_role = Admin

    {{ if .Values.auth.github.enabled }}
    [auth.github]
    enabled = {{ .Values.auth.github.enabled }}
    allow_sign_up = {{ .Values.auth.github.allowSignUp }}
    client_id = {{ .Values.auth.github.clientId }}
    client_secret = {{ .Values.auth.github.clientSecret }}
    scopes = user:email,read:org
    auth_url = https://github.com/login/oauth/authorize
    token_url = https://github.com/login/oauth/access_token
    api_url = https://api.github.com/user
    allowed_organizations={{ .Values.auth.github.allowedOrganizations }}
    {{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-grafana
data:
  dashboards.yaml: |-
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 3 #how often Grafana will scan for changed dashboards
      options:
        path: /etc/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      isDefault: true
      url: http://prometheus:9090
