---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  {{ if .Values.hasVolume }}
  volumeClaimTemplates:
  - metadata:
      name: grafana
    spec:
      storageClassName: ebs-gp2
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  {{ end }}
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccountName: grafana-dashboard
      containers:
        - name: grafana
          image: grafana/grafana:5.2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: GF_PATHS_CONFIG
              value: /etc/grafana/custom.ini
          volumeMounts:
          - name: dashboards
            mountPath: /etc/grafana/dashboards/
          {{ if .Values.hasVolume }}  
          - name: grafana-storage
            mountPath: /var/lib/grafana
            readOnly: false
          {{ end }}
          - name: grafana-ini
            mountPath: /etc/grafana
            readOnly: true
          - name: dashboard-grafana
            mountPath: /etc/grafana/provisioning/dashboards
            readOnly: true
          - name: grafana-datasource
            mountPath: /etc/grafana/provisioning/datasources
            readOnly: true
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 30
            failureThreshold: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 30
            failureThreshold: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
        - name: sidecar
          image: kiwigrid/k8s-sidecar:0.0.5
          volumeMounts:
          - name: dashboards
            mountPath: /etc/grafana/dashboards/
          env:
          - name: LABEL
            value: "grafana-dashboard/shared"
          - name: FOLDER
            value: /etc/grafana/dashboards/
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 50Mi
      securityContext:
        fsGroup: 472
      volumes:
        - name: dashboards
          emptyDir: {}
        {{ if .Values.hasVolume }}
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana
        {{ end }}    
        - name: grafana-ini
          configMap:
            name: grafana-ini
        - name: dashboard-grafana
          configMap:
            name: dashboard-grafana
        - name: grafana-datasource
          configMap:
            name: grafana-datasource
