---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  {{ if .Values.dns.enabled }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: grafana.{{ .Values.dns.domain }}.
  {{ end }}
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 3000
  selector:
    app: grafana
